server: #For spring boot config only
#    servlet:
#        session:
#            timeout: 60 #默认session过期时间,单位为秒, 但是在这里不生效，需要在代码中指定
    port: 8888 #也可以通过变量方式${port}传入，如：java -Dport=9999
management:
    health:
        elasticsearch:
            enabled: false #在引入spring-boot-starter-data-elasticsearch后spring启动后默认会对es做检查
    endpoints:
        web:
            exposure:
                include: "*" #Default for only health and info, open all now
            base-path: /actuator       #default monitor root path
    endpoint:
        health:
            show-details: always

spring:
    session: #session相关配置
        store-type: redis #指定用Redis来进行session管理，如果依赖是Redis，则默认就是Redis
        #redis:
         #   flush-mode: on_save
          #  namespace: spring-boot:session 这里指定没有生效
    boot:
        admin:
            client:
                url: http://hdp01:7777  #spring boot admin client配置地址指向admin server的运行地址，所有服务都指向这个地址
    application:
        name: spring-boot-service #muti service must be the same name but different instance id